import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NexusAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
    </head>
      <body
        className=" scroll-smooth bg-gradient-to-r from-blue-950 from-20% via-blue-950 via-70% to-red-900 to-160%  screen h-full... text-white"
        
      >
        {children}
      </body>
    </html>
  );
}
